language: node_js
before_install:
  - "export DISPLAY=:99.0"
  - sh travis/run-nflow-server.sh
  - "sh -e /etc/init.d/xvfb start"

node_js:
  - '4.1'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8

before_script:
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'
  - 'node_modules/protractor/bin/webdriver-manager update'
script: grunt && grunt itest
notifications:
  flowdock:
    secure: QbIGfsj64a2Ms5y/aTO0PUAVBRv9mKxAwLFj5NxWACEVxm1JKZvrQ4ov/8XbVRbRl96sMIoWPox7Gu++ZgLjb7w+jeiCvWLwJwRDxlCgsYvb4hAcPXlNBO7SF4kcUifPfJpaDsb3EThUUK8EtsI5aOxvCqGKMChTDoQnej3kc0o=
sudo: required
dist: trusty

cache:
  directories:
  - $HOME/.m2
