language: node_js
before_install:
  - "export DISPLAY=:99.0"
  - sh travis/run-nflow-server.sh
  - "sh -e /etc/init.d/xvfb start"
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update -qq
  - sudo apt-get install -qq google-chrome-stable

node_js:
  - '4.1'

before_script:
  - 'npm install'
  - 'node_modules/protractor/bin/webdriver-manager update'
script: npm run test && npm run itest && npm run build:prod
sudo: required
